app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mf.login.views import *

urlpatterns = [
    path('', LoginFormView.as_view(), name='index'),
    path('acceso/', include('mf.login.urls')),
    path('interno/', admin.site.urls),
    path('panel/', include('mf.crud.urls')),
    path('usuarios/', include('mf.user.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/mf/crud/urls.py
from django.urls import path
from mf.crud.views.dashboard.views import *
from mf.crud.views.companyInfo.views import *
from mf.crud.views.events.views import *
from mf.crud.views.category.views import *
from mf.crud.views.team.views import *
from mf.crud.views.player.views import *
from mf.crud.views.dettournament.views import *
from mf.crud.views.tournament.views import * 

app_name = 'crud'

urlpatterns = [
    # Dashboard
    path('inicio/', DashboardView.as_view(), name='dashboard'),
    # Company Info
    path('informacion/', CompanyInfoView.as_view(), name='companyinfo'),
    # Calendar
    path('eventos/list/', EventosListView.as_view(), name='events'),
    # NEW URLS
    # Category
    path('categorias/list/', CategoryListView.as_view(), name='category_list'),
    # Teams
    path('teams/list/', TeamListView.as_view(), name='team_list'),
    # Tournaments
    path('torneos/list/', TournamentListView.as_view(), name='tornauments'),
    # Dettournament
    path('torneos/list/<int:idTournament>/<int:roundNumber>/', DetTournamentistView.as_view(), name='tornauments_list'),
    # Players
    path('jugadores/', PlayerView.as_view(), name='player')
]

app/mf/user/urls.py
from django.urls import path
from mf.user.views import *
# from mf.crud.views.tests.views import TestView

app_name = 'user'

urlpatterns = [
    # Users
    path('list/', UserListView.as_view(), name='users_list'),
]

app/mf/crud/models.py
from django.core.files.storage import FileSystemStorage
from crum import get_current_user, get_current_request
from mf.user.models import User
from django.db import models
from datetime import datetime
from django.utils import timezone 
from datetime import date
from django.forms import model_to_dict
from config.settings import MEDIA_URL, STATIC_URL
from mf.models import BaseModel
from django.utils.dateparse import parse_datetime
import pytz

IDENTITY_CHOICES = [
    ('V', 'V'),
    ('J', 'J'),
    ('E', 'E'),
    ('G', 'G'),
    ('FP', 'FP'),
]

SYMBOL_CHOICES = [
    ('Bs', 'Bs'),
    ('$', '$'),
]

STATUS_CHOICES = [
    ('ACTIVO', 'ACTIVO'),
    ('INACTIVO', 'INACTIVO'),
]

GENDER_CHOICES = [
    ('FEMENINO', 'FEMENINO'),
    ('MASCULINO', 'MASCULINO'),
]

class Permisology(models.Model):
    name = models.CharField(max_length=255, verbose_name='Permiso')
    description = models.CharField(max_length=255, verbose_name='Descripción')
    day = models.DateField(max_length=50, default=date.today().strftime('%Y-%m-%d'), verbose_name='Fecha de pago')
    color = models.CharField(max_length=250, default='#007bff', verbose_name='Color')

    def __str__(self):
        return self.name

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        verbose_name = 'Permisos y Eventos'
        verbose_name_plural = 'Permisos y Eventos'
        ordering = ['id']

class CompanyInfo(models.Model):
    name = models.CharField(max_length=225, verbose_name="Razón Social")
    comercialName = models.CharField(max_length=225, verbose_name="Nombre Comercial")
    nit = models.CharField(max_length=225, verbose_name="NIT")
    address = models.CharField(max_length=225, verbose_name="Dirección Fiscal")
    city = models.CharField(max_length=225, verbose_name="Ciudad")
    phone = models.CharField(max_length=255, verbose_name="Telefono(s)")
    email = models.CharField(max_length=255, verbose_name="Correo")
    services = models.TextField(verbose_name="Servicios")
    logo = models.ImageField(upload_to='img/logo', null=True, blank=True)
    logoInvoice = models.ImageField(upload_to='img/logo', null=True, blank=True)

    def __str__(self):
        return '{}.{}'.format(self.name, self.nit)
    
    def toJSON(self):
        item = model_to_dict(self)
        item['logo'] = str(self.logo)
        item['logoInvoice'] = str(self.logoInvoice)
        return item
    
    class Meta:
        verbose_name = "Información de la Empresa"
        ordering = ['id']

class Eventos(models.Model):
    name = models.CharField(max_length=255, verbose_name='Evento')
    description = models.CharField(max_length=255, verbose_name='Descripción')
    day = models.DateField(max_length=50, default=date.today().strftime('%Y-%m-%d'), verbose_name='Fecha')
    color = models.CharField(max_length=250, default='#007bff', verbose_name='Color')

    def __str__(self):
        return self.name

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        verbose_name = 'Eventos'
        verbose_name_plural = 'Eventos'
        ordering = ['id']

# NEW MODELS

class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Categoría', unique=True)
    description = models.TextField(verbose_name="Descripción")
    status = models.IntegerField(default=1)

    def __str__(self):
        return self.name

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        verbose_name = 'Categoría'
        verbose_name_plural = 'Categorías'
        ordering = ['id']

# Model for Competitor
class Team(models.Model):
    name = models.CharField(max_length=150, verbose_name='Nombre y Apellido')
    dni = models.CharField(max_length=150, verbose_name='Cédula de Identidad')
    birthdate = models.DateField(max_length=50, default=date.today().strftime('%Y-%m-%d'), verbose_name='Fecha de Nacimiento')
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default='Masculino', verbose_name="Género")
    email = models.EmailField(max_length=150, verbose_name='Correo')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name="Categoría")
    logo = models.ImageField(upload_to='img/team', null=True, blank=True)
    status = models.IntegerField(default=1)

    def __str__(self):
        return '{} ({})'.format(self.name, self.category.name)
    
    def toJSON(self):
        item = model_to_dict(self)
        item['category'] = self.category.toJSON()
        item['logo'] = str(self.logo)
        return item
    
    class Meta:
        verbose_name = 'Equipo'
        verbose_name_plural = 'Equipos'
        ordering = ['id']

class Player(models.Model):
    team = models.ForeignKey(Team, on_delete=models.PROTECT, verbose_name="Equipo")
    name = models.CharField(max_length=150, verbose_name='Nombre del Jugador')
    status = models.IntegerField(default=1)

    def __str__(self):
        return '{}.{}'.format(self.name)
    
    def toJSON(self):
        item = model_to_dict(self)
        item['team'] = self.team.toJSON()
        return item
    
    class Meta:
        verbose_name = 'Jugador'
        verbose_name_plural = 'Jugadores'
        ordering = ['id']

class Tournament(models.Model):
    name = models.CharField(max_length=255, verbose_name="Nombre del Torneo")
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name="Categoría")
    datejoined = models.DateField(max_length=10, default=date.today().strftime('%Y-%m-%d'), verbose_name="Fecha")
    qtyLosses = models.IntegerField(default=0, verbose_name="Número de Pérdidas")
    status = models.IntegerField(default=0)
    cantidad = models.IntegerField(default=1)

    def __str__(self):
        return '{} ({})'.format(self.name, self.category.name)

    def toJSON(self):
        item = model_to_dict(self)
        item['category'] = self.category.toJSON()
        item['det'] = [i.toJSON() for i in self.dettournament_set.all()]
        return item
    
    class Meta:
        verbose_name = 'Torneo'
        verbose_name_plural = 'Torneos'
        ordering = ['id']

class DetTournament(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    plays = models.IntegerField(default=0)
    earned = models.IntegerField(default=0)
    losses = models.IntegerField(default=0)
    tied = models.IntegerField(default=0)
    removed = models.IntegerField(default=0)
    points = models.IntegerField(default=0)
    lastOpponent = models.ForeignKey(Team, null=True, blank=True, on_delete=models.CASCADE, related_name="lastOpponent")

    def __str__(self):
        return self.tournament.name
    
    def toJSON(self):
        item = model_to_dict(self, exclude=['tournament'])
        item['team'] = self.team.toJSON()
        if self.lastOpponent is not None:
            item['lastOpponent'] = self.lastOpponent.toJSON()
        return item

    class Meta:
        verbose_name = 'Detalle de Torneo'
        verbose_name_plural = 'Detalle de Torneos'
        ordering = ['id']

class Confrontations(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.PROTECT)
    team1 = models.ForeignKey(Team, on_delete=models.PROTECT, related_name="Team1")
    team2 = models.ForeignKey(Team, on_delete=models.PROTECT, related_name="Team2")
    roundNumber = models.IntegerField(default=0)
    qtyRound1 = models.IntegerField(default=0)
    qtyRound2 = models.IntegerField(default=0)
    status = models.IntegerField(default=0)

    def __str__(self):
        return self.tournament.name
    
    def toJSON(self):
        item = model_to_dict(self, exclude=['tournament'])
        item['team1'] = self.team1.toJSON()
        item['team2'] = self.team2.toJSON()
        item['det'] = [i.toJSON() for i in self.detconfrontations_set.all()]
        return item

    class Meta:
        verbose_name = 'Enfrentamiento'
        verbose_name_plural = 'Enfrentamientos'
        ordering = ['id']

class Ridding(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.PROTECT)
    team = models.ForeignKey(Team, on_delete=models.PROTECT)
    roundNumber = models.IntegerField(default=0)
    free = models.IntegerField(default=0)
    status = models.IntegerField(default=1)

    def __str__(self):
        return self.roundNumber
    
    def toJSON(self):
        item = model_to_dict(self, exclude=['tournament'])
        item['team'] = self.team.toJSON()
        return item

    class Meta:
        verbose_name = 'Equipo Librando'
        verbose_name_plural = 'Equipos Librando'
        ordering = ['id']

class DetConfrontations(models.Model):
    confrontation = models.ForeignKey(Confrontations, on_delete=models.PROTECT)
    winner = models.ForeignKey(Team, on_delete=models.PROTECT, related_name="WinningTeam")
    loser = models.ForeignKey(Team, on_delete=models.PROTECT, related_name="LosingTeam")

    def __str__(self):
        return self.confrontation.name
    
    def toJSON(self):
        item = model_to_dict(self, exclude=['confrontation'])
        item['winner'] = self.winner.toJSON()
        item['loser'] = self.loser.toJSON()
        return item

    class Meta:
        verbose_name = 'Detalle de Enfrentamiento'
        verbose_name_plural = 'Detalle de Enfrentamientos'
        ordering = ['id']

app/mf/crud/views/dashboard/views.py
from django.views.generic import TemplateView
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from urllib import request
from django.utils import timezone
from django.db import transaction
from config.settings import MEDIA_URL

from django.contrib.auth.mixins import LoginRequiredMixin
from mf.crud.mixins import IsSuperuserMixin, ValidatePermissionMixin

from datetime import date
from datetime import datetime, timedelta

from mf.crud.models import Tournament
from django.db.models.functions import Coalesce
from django.db.models import Sum

from mf.crud.functions import *

import os
from pathlib import Path

class DashboardView(LoginRequiredMixin, ValidatePermissionMixin, TemplateView):
    template_name = 'dashboard.html'
    permission_required = 'view_tournament'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            db = 'default'
            action = request.POST['action']
            if action == 'get_graph_sales':
                year = datetime.now().year
                for m in range(1, 13):
                    total = Tournament.objects.filter(datejoined__year=year, datejoined__month=m).aggregate(
                        r=Coalesce(Sum('cantidad'), 0)).get('r')
                data = {
                    'name': 'Porcentaje de Torneos',
                    'showInLegend': False,
                    'colorByPoint': True,
                    'data': self.get_graph_sales()
                }
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)
    
    
    def get_graph_sales(self):
        data = []
        try:
            year = datetime.now().year
            for m in range(1, 13):
                total = Tournament.objects.filter(datejoined__year=year, datejoined__month=m).aggregate(
                    r=Coalesce(Sum('cantidad'), 0)).get('r')
                data.append(float(total))
        except:
            pass
        return data

    def get_name_month(self):
        data = ''
        month = datetime.now().month
        if month == 1:
            data = 'Enero'
        elif month == 2:
            data = 'Febrero'
        elif month == 3:
            data = 'Marzo'
        elif month == 4:
            data = 'Abril'
        elif month == 5:
            data = 'Mayo'
        elif month == 6:
            data = 'Junio'
        elif month == 7:
            data = 'Julio'
        elif month == 8:
            data = 'Agosto'
        elif month == 9:
            data = 'Septiembre'
        elif month == 10:
            data = 'Octubre'
        elif month == 11:
            data = 'Noviembre'
        elif month == 12:
            data = 'Diciembre'
        return data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel'] = 'PRINCIPAL'
        context['today'] = date.today()
        context['month'] = self.get_name_month()
        context['year'] = datetime.now().year
        context['title_pag'] = 'Panel principal'
        context['title'] = 'INICIO'
        context['events'] = get_events_today()
        context['q_events'] = get_q_events_today()
        context['data'] = getCompanyData()
        return context

app/templates/body.html
{% extends 'home.html' %}
{% block body %}
<body class="hold-transition sidebar-mini layout-fixed sidebar-collapse">
    <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Sidebar -->
        {% include 'sidebar.html' %}
        <!-- Content -->
        {% block wrapper %}
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">{{ title_pag }}</h1>
                        </div>
                    </div>
                </div>
            </div>
        {% endblock %}
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
<script>
'{% if messages %}'
    var html = '<p>';
    '{% for msg in messages %}'
        html += '{{ msg }}<br>';
    '{% endfor  %}'
    html += '</p>';
    alertSweetError(html);
'{% endif %}'
</script>
</body>
{% endblock %}

app/templates/dashboard.html
{% extends 'layout.html' %} {% load static %} {% load humanize %} {% block head %}
<script src="{% static 'lib/highcharts-8.2.0/highcharts.js' %}"></script>
<script src="{% static 'lib/highcharts-8.2.0/modules/exporting.js' %}"></script>
<script src="{% static 'lib/highcharts-8.2.0/modules/export-data.js' %}"></script>
<script src="{% static 'lib/highcharts-8.2.0/modules/accessibility.js' %}"></script>

<link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}" />
<link rel="stylesheet"
    href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}" />
<script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'lib/sweetalert2/sweetalert2@10.js' %}"></script>
<script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>
<!-- <script src="https://s3.amazonaws.com/dolartoday/data.json"></script> -->

<script src="{% static 'js/dashboard/functions.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>
{% endblock %} {% block wrapper %} {% endblock %} {% block content %}
<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid"></div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3 col-6">
                <div class="small-box box-shadow">
                    <div class="inner">
                        <h3></i> FECHA</h3>
                        <p>{{ today }}</p>
                    </div>
                    <div class="icon">
                        <i class="ion">
                            <ion-icon src="{% static 'lib/ionicons/svg/calendar-outline.svg' %}"></ion-icon>
                        </i>
                    </div>
                    <a href="{% url 'crud:events' %}" class="small-box-footer">Revisar calendario <i
                            class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-6">
                <div class="small-box box-shadow">
                    <div class="inner">
                        <h3>CATEGORÍAS</h3>
                        <p>Gestionar listado</p>
                    </div>
                    <div class="icon">
                        <i class="ion">
                            <ion-icon src="{% static 'lib/ionicons/svg/bookmarks-outline.svg' %}"></ion-icon>
                        </i>
                    </div>
                    <a href="{% url 'crud:category_list' %}" class="small-box-footer">Ir al módulo <i
                            class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-6">
                <div class="small-box box-shadow">
                    <div class="inner">
                        <h3>PARTICIPANTES</h3>
                        <p>Gestionar participantes</p>
                    </div>
                    <div class="icon">
                        <i class="ion">
                            <ion-icon src="{% static 'lib/ionicons/svg/people-outline.svg' %}"></ion-icon>
                        </i>
                    </div>
                    <a href="{% url 'crud:team_list' %}" class="small-box-footer">Ir al módulo <i
                            class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-6">
                <div class="small-box box-shadow">
                    <div class="inner">
                        <h3>TORNEOS</h3>
                        <p>Gestionar torneos</p>
                    </div>
                    <div class="icon">
                        <i class="ion">
                            <ion-icon src="{% static 'lib/ionicons/svg/medal-outline.svg' %}"></ion-icon>
                        </i>
                    </div>
                    <a href="{% url 'crud:tornauments' %}" class="small-box-footer">Ir al módulo <i
                            class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header card-header-graph ui-sortable-handle" style="cursor: move;">
                        <h3 class="card-title">
                            <i class="fas fa-chart-pie mr-1"></i> AÑO ACTUAL ({{ year }})
                        </h3>
                    </div>
                    <div class="card-body card-body-graph">
                        <div id="container" class="box-shadow"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="application/javascript">
    var graphcolumn = Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        lang: {
            viewFullscreen: "Ver en pantalla completa",
            printChart: "Imprimir gráfica",
            downloadPNG: "Descargar Imagen PNG",
            downloadJPEG: "Descargar Imagen JPEG",
            downloadPDF: "Descargar Documento PDF",
            downloadSVG: "Descargar Vector SVG",
            downloadCSV: "Descarga CSV",
            downloadXLS: "Descarga XLS",
            viewData: "Ver datos del Análisis",
            hideData: "Ocultar datos del Análisis",
            thousandsSep: ","
        },
        title: {
            text: 'Torneos durante el año actual'
        },
        subtitle: {
            text: 'Análisis gráfico de torneos por mes'
        },
        xAxis: {
            title: {
                text: 'Mes'
            },
            categories: [
                'Enero',
                'Febrero',
                'Marzo',
                'Abril',
                'Mayo',
                'Junio',
                'Julio',
                'Agosto',
                'Septiembre',
                'Octubre',
                'Noviembre',
                'Diciembre'
            ],
            crosshair: true
        },
        yAxis: {
            min: 0,
            max: 30,
            title: {
                text: 'Torneos'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:,.2f} </b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
    });
</script>
{% endblock %}

app/templates/footer.html
<!-- Main Footer -->
<footer class="main-footer text-center">
    <strong>Copyright &copy; 2020-2021 <a href="https://fulldev.es/">FullDev - WebDesign</a>.</strong><br>
    Todos los derechos reservados.
</footer>

app/templates/header.html
{% load static %}
{% load humanize %}
<nav class="main-header navbar navbar-expand">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" id="pushmenu" onclick="display_logo()" data-widget="pushmenu" href="#" role="button"><i
                    id="icon-expand" class="fas fa-bars text-white" style="font-size: 20px!important;"></i></a>
        </li>
        <li class="nav-item dropdown" style="margin: 5px;">
            <!-- <small class="text-m2 text-white">Tasa ($): {{ dl.dolar1|floatformat:2 }} bs</small> -->
        </li>
    </ul>

    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown" id="calendar-notifications" style="margin: 5px;">
            <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
                <i class="far fa-bell text-white" style="font-size: 1.3em;"></i>
                <span class="badge badge-warning navbar-badge">{{ q_events }}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" style="left: inherit; right: 0px;">
                {% for i in events %}
                <a href="{% url 'crud:events' %}" class="dropdown-item">
                    <i class="fas fa-calendar-alt mr-2"></i> {{ i.name|slice:":19" }}...
                    <span class="float-right text-muted text-sm">{{ i.day }}</span>
                </a>
                <hr>
                {% endfor %}
                <a href="{% url 'crud:events' %}" class="dropdown-item dropdown-footer bg-secondary">Ir al
                    Calendario</a>
        </li>
        <li class="nav-item" id="user-info" style="margin-top: 5px; padding-left: 0px!important;">
            <a class="nav-link text-white pointer-1" href="#">
                {{ request.user|upper }} <i class="fas fa-user text-white" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

app/templates/layout.html
{% extends 'body.html' %}

app/templates/sidebar.html
{% load static %} {% load humanize %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <div class="sidebar">
        <div class="text-center img-logo-mf">
            <a href="{% url 'crud:dashboard' %}">
                <!-- <img id="img-sidebar-collapsed" src="https://torneos-a56c288d2a31.herokuapp.com/static/img/medalla-1.png" alt="logo" class="img-fluid"> -->
                <img id="img-sidebar-collapsed" src="{% static 'img/icon-tartarus.png' %}" alt="logo" class="img-fluid">
            </a>
        </div>
        <!-- <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-header text-white">
                <h5><b>{{ data.name }}</b></h5>
            </li>
        </ul> -->
        <nav class="mt-2">
            <hr class=" hr_division">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header"><b>PÁGINA PRINCIPAL</b></li>
                <li class="nav-item">
                    <a href="{% url 'crud:dashboard' %}" class="nav-link">
                        <i class="nav-icon fas fa-home"></i>
                        <p class="p-nav">
                            INICIO
                        </p>
                    </a>
                </li>
                <hr class="hr_division">
            </ul>
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header"><b>CALENDARIO</b></li>
                <li class="nav-item">
                    <a href="{% url 'crud:events' %}" class="nav-link">
                        <i class="nav-icon fas fa-calendar-alt"></i>
                        <p class="p-nav">
                            Eventos
                        </p>
                    </a>
                </li>
                <hr class="hr_division">
            </ul>
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header"><b>CONFIGURACIÓN</b></li>
                <li class="nav-item">
                    <a href="{% url 'crud:category_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-globe"></i>
                        <p class="p-nav">
                            Categorías
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'crud:team_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p class="p-nav">
                            Participantes
                        </p>
                    </a>
                </li>
                <!-- <li class="nav-item">
                    <a href="{% url 'crud:player' %}" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p class="p-nav">
                            Jugadores
                        </p>
                    </a>
                </li> -->
                <li class="nav-item">
                    <a href="{% url 'crud:tornauments' %}" class="nav-link">
                        <i class="nav-icon fas fa-trophy"></i>
                        <p class="p-nav">
                            Torneos
                        </p>
                    </a>
                </li>
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header"><b></b>TABLAS DE GESTIÓN</b></li>
                <li class="nav-item">
                    <a href="{% url 'crud:companyinfo' %}" class="nav-link">
                        <i class="nav-icon fas fa-building"></i>
                        <p class="p-nav">
                            Empresa
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'user:users_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-user"></i>
                        <p class="p-nav">
                            Usuarios
                        </p>
                    </a>
                </li>
                <hr class="hr_division">
            </ul>
            <!-- <hr class="hr_division"> -->
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header"><b></b>SALIR</b></li>
                <li class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link">
                        <i class="nav-icon fas fa-power-off"></i>
                        <p class="p-nav">
                            Cerrar sesión
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>